// src/App.tsx
import React from 'react';
import './App.css';

import { FaPlay, FaPause, FaStop } from 'react-icons/fa';
import update from 'immutability-helper';
import styled from 'styled-components'
import { Synth, PolySynth, Part, Transport } from 'tone';

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Keyboard = styled.div`
  display: flex;
  flex-direction: row;
  height: 200px;
  border: 5px solid black;
`;

const Octave = styled.div`
  display: flex;
  flex-direction: row;
`;

interface ButtonProps {
  pressed?: boolean
}

const Whitekey = styled.div<ButtonProps>`
  position: relative;
  height: 100%;
  width: 50px;
  background: ${props => props.pressed ? '#CCC' : 'white'};
  float: left;
  border-right: 1px solid black;
`;

const Blackkey = styled.div<ButtonProps>`
  position: absolute;
  height: 65%;
  width: 55%;
  z-index: 1;
  background: ${props => props.pressed ? '#CCC' : '#444'};
  left: 68%;
`;

const Staff = styled.div`
  width: 80%;
  display: flex;
  flex-direction: row;
  margin: 16px;
`

const Bar = styled.div`
  display: flex;
  flex-direction: row;
  align-items: flex-end;
`

const Beat = styled.div`
  display: flex;
  flex-direction: column;
`

const Line = styled.div`
  height: 2px;
  background: black;
  display: flex;
  flex-direction: row;
  align-items: center;
`

const Space = styled.div`
  height: 12px;
  background: white;
  display: flex;
  flex-direction: row;
  align-items: center;
`

interface NoteProps {
  sharp?: boolean;
}

const Note = styled.div<NoteProps>`
  height: 10px;
  width: 10px;
  background: black;
  border-radius: 5px;
  margin: 0 5px;
  z-index: 1;
  display: flex;
  flex-direction: row;
  ::after {
    content: ${props => props.sharp ? "'#'" : "''"};
    position: relative;
    left: 10px;
    top: -5px;
  }
`

interface State {
  keyPressed: { [key: string]: boolean }
  history: Array<string>
  playing: boolean
  paused: boolean
}

export default class App extends React.Component<{}, State> {

  synth: PolySynth = new PolySynth({ maxPolyphony: 10, voice: Synth }).toDestination()
  playback?: Part
  notes = ['C', 'D', 'E', 'F', 'G', 'A', 'B']
  keybindings = {
    4: "zxcvbnm",
    5: "asdfghj",
    6: "qwertyu",
  }

  constructor(props: any) {
    super(props);
    this.state = {
      keyPressed: {},
      history: [],
      playing: false,
      paused: false,
    }
  }

  onKeyDown(event: React.KeyboardEvent) {
    for (let octave of Object.entries(this.keybindings)) {
      const i = octave[1].indexOf(event.key.toLowerCase());
      if (i >= 0) {
        let note = this.notes[i];
        if (note !== 'E' && note !== 'B' && event.shiftKey) note += '#';
        note += parseInt(octave[0]);
        if (this.state.keyPressed[note]) return;
        this.startNote(note)(event);
      }
    }
  }

  onKeyUp(event: React.KeyboardEvent) {
    if (event.key === 'Backspace') {
      this.setState(update(this.state, { history: { $splice: [[this.state.history.length - 1, 1]] } }));
    }
    for (let octave of Object.entries(this.keybindings)) {
      const i = octave[1].indexOf(event.key.toLowerCase());
      if (i >= 0) {
        let note = this.notes[i];
        if (note !== 'E' && note !== 'B' && event.shiftKey) note += '#';
        note += parseInt(octave[0]);
        this.stopNote(note)(event);
      }
    }
  }

  startNote(note: string) {
    return (event: React.SyntheticEvent) => {
      this.synth.triggerAttack([note]);
      event.stopPropagation();
      this.setState({
        ...this.state,
        history: update(this.state.history, { $push: [note] }),
        keyPressed: update(this.state.keyPressed, { [note]: { $set: true } }),
      });
    }
  }

  stopNote(note: string) {
    return (event: React.SyntheticEvent) => {
      this.synth.triggerRelease([note]);
      event.stopPropagation();
      this.setState({
        ...this.state,
        keyPressed: update(this.state.keyPressed, { [note]: { $set: false } }),
      });
    }
  }

  onPlay() {
    if (this.state.paused) {
      Transport.start();
    } else {
      Transport.start();
      this.playback = new Part((time, event) => {
        this.synth.triggerAttackRelease(event.note, event.dur, time);
        if (event.time === this.state.history.length - 1) {
          this.onStop();
        }
      }, this.state.history.map((note, i) => {
        return { time: i * 0.25, note: note, dur: '16n' };
      }));
      this.playback.start(0);
    }
    this.setState({
      ...this.state,
      playing: true,
      paused: false,
    });
  }

  onPause() {
    Transport.pause();
    this.setState({
      ...this.state,
      paused: true,
    });
  }

  onStop() {
    this.playback?.stop();
    Transport.stop();
    this.setState({
      ...this.state,
      playing: false,
    });
  }

  render() {
    const octaves = [
      this.notes.map(note => note + 4),
      this.notes.map(note => note + 5),
      this.notes.map(note => note + 6),
    ];
    return (
      <Container onKeyDown={this.onKeyDown.bind(this)} onKeyUp={this.onKeyUp.bind(this)} tabIndex={-1}>
        <div>
          {(!this.state.playing || this.state.paused) ? <FaPlay onClick={this.onPlay.bind(this)} /> : <FaPause onClick={this.onPause.bind(this)} />}
          {this.state.playing && <FaStop onClick={this.onStop.bind(this)} />}
        </div>
        <Staff>
          <Bar>
            {this.state.history.map((active, i) => <Beat key={i}>
              {octaves.flat().reverse().map((note, j) => {
                if (j % 2 === 0) {
                  return <Line key={j}>{note[0] === active[0] && note[note.length - 1] === active[active.length - 1] && <Note sharp={active.includes('#')} />}</Line>;
                }
                return <Space key={j}>{note[0] === active[0] && note[note.length - 1] === active[active.length - 1] && <Note sharp={active.includes('#')} />}</Space>;
              })}
            </Beat>
            )}
          </Bar>
        </Staff>
        <Keyboard>
          {octaves.map((notes, i) => <Octave key={i}>
            {notes.map((note, i) => {
              let blackKey = null;
              if (note[0] !== 'E' && note[0] !== 'B') {
                const sharp = note[0] + '#' + note[1];
                blackKey = <Blackkey key={i} pressed={this.state.keyPressed[sharp]} onMouseDown={this.startNote(sharp)} onMouseUp={this.stopNote(sharp)} />;
              }
              return <Whitekey key={i} pressed={this.state.keyPressed[note]} onMouseDown={this.startNote(note)} onMouseUp={this.stopNote(note)}>
                {blackKey}
              </Whitekey>;
            })}
          </Octave>)}
        </Keyboard>
      </Container>
    );
  }
};

// src/App.svelte
<script lang="ts">
	import type { Sampler } from "tone";
	import Samples from "./Samples";

	const octaves = [4, 5, 6];
	const tones = ["C", "D", "E", "F", "G", "A", "B"];
	const keyBindings = ["zxcvbnm", "asdfghj", "qwertyu"];
	const notesPlaying: { [key: string]: Date } = {};

	const samples = new Samples();

	let instrument: Sampler | undefined;
	samples.instrument("piano").then((sampler) => {
		instrument = sampler;
		instrument.toDestination();
	});

	function note(tone: string, octave: number, sharp?: boolean): string {
		return `${tone}${
			tone !== "E" && tone !== "B" && sharp ? "#" : ""
		}${octave}`;
	}

	function onKeyDown(event: KeyboardEvent) {
		keyBindings.forEach((binding, octaveOffset) => {
			const i = binding.indexOf(event.key.toLowerCase());
			if (i >= 0) {
				const tone = tones[i];
				const octave = octaves[0] + octaveOffset;
				const n = note(tone, octave, event.shiftKey);
				if (notesPlaying[n]) return;
				notesPlaying[n] = new Date();
				instrument.triggerAttack([n]);
			}
		});
	}

	function onKeyUp(event: KeyboardEvent) {
		keyBindings.forEach((binding, octaveOffset) => {
			const i = binding.indexOf(event.key.toLowerCase());
			if (i >= 0) {
				const tone = tones[i];
				const octave = octaves[0] + octaveOffset;
				const n = note(tone, octave, event.shiftKey);
				notesPlaying[n] = undefined;
				instrument.triggerRelease([n]);
			}
		});
	}

	function start(note: string) {
		return (event: MouseEvent) => {
			instrument.triggerAttack([note]);
			event.stopPropagation();
		};
	}

	function stop(note: string) {
		return (event: MouseEvent) => {
			instrument.triggerRelease([note]);
			event.stopPropagation();
		};
	}
</script>

<main>
	<div class="keyboard" on:keydown={onKeyDown} on:keyup={onKeyUp}>
		{#each octaves as octave}
			{#each tones as tone}
				<div class="key">
					{#if tone !== "E" && tone !== "B"}
						<button
							on:mousedown={start(note(tone, octave, true))}
							on:mouseup={stop(note(tone, octave, true))}
							class="blackkey"
						/>
					{/if}
					<button
						on:mousedown={start(note(tone, octave))}
						on:mouseup={stop(note(tone, octave))}
						class="whitekey"
					/>
				</div>
			{/each}
		{/each}
	</div>
</main>

<style>
	main {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		width: 100vw;
		height: 100vh;
	}

	.keyboard {
		margin: 0 auto;
		display: flex;
		flex-direction: row;
		height: 200px;
	}

	.key {
		position: relative;
	}

	.whitekey {
		height: 100%;
		min-width: 50px;
		background: "white";
		border: 1px solid black;
	}

	.blackkey {
		position: absolute;
		height: 65%;
		min-width: 30px;
		z-index: 1;
		background: #444;
		left: 35px;
		top: 0px;
	}
</style>
